apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
    - image: mycv
  local:
    push: true
    useBuildkit: false
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
      - k8s/mycv-deploy.yml
      - k8s/mycv-svc.yml
      - k8s/mycv-secret.yml
