apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: ylogosha/mycv
deploy:
  kubectl:
    manifests:
    - k8s/mycv-deploy.yml
    - k8s/mycv-svc.yml
    - k8s/mycv-ingress.yml
    - k8s/mycv-secret.yml
